"""fix store delete

Revision ID: 785030949d1e
Revises: 2ad76c72a0c5
Create Date: 2024-12-17 15:59:04.230610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785030949d1e'
down_revision = '2ad76c72a0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjust the foreign key to include ON DELETE CASCADE
    with op.batch_alter_table('items', schema=None) as batch_op:
        # Drop the existing foreign key constraint
        batch_op.drop_constraint('items_store_id_fkey', type_='foreignkey')

        # Recreate the foreign key with ON DELETE CASCADE
        batch_op.create_foreign_key(
            'items_store_id_fkey',  # Constraint name
            'stores',               # Referenced table
            ['store_id'],           # Local column
            ['id'],                 # Referenced column
            ondelete='CASCADE'      # ON DELETE CASCADE
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_store_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'items_store_id_fkey', 'stores', ['store_id'], ['id']
        )

    # ### end Alembic commands ###
