"""add indexes

Revision ID: b354e30ccd5d
Revises: 785030949d1e
Create Date: 2024-12-18 21:26:24.913346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b354e30ccd5d'
down_revision = '785030949d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)
        batch_op.drop_constraint('items_store_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_name'))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_store_id_fkey', 'stores', ['store_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_items_name'))

    # ### end Alembic commands ###
